### ISSUE TITLE
Invalid server requirements.txt

### ISSUE THREAD

**Issue by alexkillen** [OpenNMT/nmt-wizard#67]
The server/requirements.txt file includes two built-in Python modules which prevent a "pip install -r requirements.txt" from working:

- shutil
- hashlib

Also, the "pymongo" package appears to be needed, as nmt-wizard/helper.py makes use of it, but it's not included in the requirements.txt.  This one seems a bit odd to me as I don't see any mention of MongoDB as a requirement in the README.

**Comment by nguyendc-systran** [comment]
Thanks for your report.
The requirements.txt is cleaned up now.
"pymongo" is not needed here, actually this is only required by an internal project in our side. We might think to remove the related code from this project. So don't worry about this dependency.
